import type { AnalysisResult } from '../types';
import { gradeColor, severityBadgeClass } from '../lib/utils';
import { Shield, Download, Clock, TrendingUp, FlaskConical, Settings2, Trophy, FileText } from 'lucide-react';
import HealthScoreCard from '../components/HealthScoreCard';
import { useEffect, useState } from 'react';

interface Props { result: AnalysisResult }

function SummaryItem({ label, value, color = 'text-white' }: { label: string; value: number; color?: string }) {
  const [animated, setAnimated] = useState(0);
  useEffect(() => {
    const t = setTimeout(() => setAnimated(value), 150);
    return () => clearTimeout(t);
  }, [value]);
  return (
    <div className="text-center p-4 rounded-xl bg-gray-800/30 border border-gray-700/30">
      <p className={`text-3xl font-black tabular-nums ${color}`} style={{ transition: 'all 0.5s' }}>{animated}</p>
      <p className="text-xs text-gray-500 mt-1 font-medium">{label}</p>
    </div>
  );
}

export default function ReportPage({ result }: Props) {
  const { repositoryProfile: meta, testProfile, configHealth, priorityFindings, healthScore, testGaps } = result;

  function downloadJson() {
    const serializable = {
      ...result,
      testProfile: { ...result.testProfile, coveredFiles: Array.from(result.testProfile.coveredFiles) },
    };
    const blob = new Blob([JSON.stringify(serializable, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `doctor-dev-report-${meta.name}-${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadMarkdown() {
    const lines: string[] = [
      `# 🩺 Doctor Dev Health Report — ${meta.name}`,
      ``,
      `> **Generated:** ${new Date(result.scannedAt).toLocaleString()}  `,
      `> **Analysis ID:** \`${result.analysisId}\``,
      ``,
      `---`,
      ``,
      `## 📊 Health Score`,
      ``,
      `| Metric | Value |`,
      `|--------|-------|`,
      `| **Overall** | **${healthScore.overall}/100** |`,
      `| Grade | **${healthScore.grade}** |`,
      `| Testing | ${healthScore.testing}/100 |`,
      `| Configuration | ${healthScore.configuration}/100 |`,
      `| Security | ${healthScore.security}/100 |`,
      `| State | ${healthScore.state.replace(/_/g, ' ')} |`,
      ``,
      `---`,
      ``,
      `## 📁 Repository`,
      ``,
      `| Property | Value |`,
      `|----------|-------|`,
      `| Language | ${meta.language} |`,
      `| Framework | ${meta.framework ?? 'N/A'} |`,
      `| Package Manager | ${meta.packageManager} |`,
      `| Test Frameworks | ${meta.testFrameworks.join(', ') || 'None'} |`,
      `| Source Files | ${meta.sourceFiles.length} |`,
      `| Test Files | ${meta.testFiles.length} |`,
      ``,
      `---`,
      ``,
      `## 🔬 TestPilot — Testing Gaps (${testGaps.length})`,
      ``,
      ...testGaps.slice(0, 20).map((g) =>
        `### [${g.severity.toUpperCase()}] ${g.title}\n\n- **File:** \`${g.filePath}\`\n- **Reason:** ${g.reason}\n- **Recommended tests:**\n${g.recommendedTests.map((t) => `  - \`it('${t}', ...)\``).join('\n')}\n`
      ),
      `---`,
      ``,
      `## ⚙️ ConfigDoctor — Configuration Issues (${configHealth.issues.length})`,
      ``,
      ...configHealth.issues.slice(0, 20).map((i) =>
        `### [${i.severity.toUpperCase()}] ${i.title}\n\n${i.description}\n\n**Fix:** ${i.recommendedFix}\n`
      ),
      `---`,
      ``,
      `## 🚨 Priority Findings`,
      ``,
      ...priorityFindings.map((f) =>
        `### ${f.level.toUpperCase()}: ${f.title}\n\n${f.description}\n\n**Recommendation:** ${f.recommendation}\n\n**Impact:** ${f.estimatedImpact}\n`
      ),
      `---`,
      ``,
      `*Report generated by Doctor Dev — AI Software Health Checker*`,
      `*IBM Bob 2.0 Hackathon 2026*`,
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `doctor-dev-report-${meta.name}-${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const criticalCount = priorityFindings.filter((f) => f.level === 'critical').length;
  const highCount = priorityFindings.filter((f) => f.level === 'high').length;

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Report header */}
      <div className="relative overflow-hidden rounded-2xl border border-gray-800/60 p-6"
        style={{ background: 'linear-gradient(135deg, rgba(17,24,39,0.9), rgba(11,17,32,0.95))' }}>
        <div className="absolute inset-0 bg-grid opacity-30" />
        <div className="absolute top-0 right-0 w-64 h-64 opacity-5 blur-3xl rounded-full"
          style={{ background: 'radial-gradient(circle, #3b82f6, transparent)' }} />
        <div className="relative flex items-start justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl border border-blue-800/40 bg-blue-950/30 flex items-center justify-center">
              <Shield className="w-6 h-6 text-blue-400" />
            </div>
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wider font-semibold mb-0.5">Doctor Dev Health Report</p>
              <h2 className="text-xl font-black text-white">{meta.name}</h2>
              <div className="flex items-center gap-2 mt-1 text-xs text-gray-600">
                <Clock className="w-3 h-3" />
                <span>{new Date(result.scannedAt).toLocaleString()}</span>
                <span className="text-gray-800">·</span>
                <FileText className="w-3 h-3" />
                <span>ID: {result.analysisId.slice(0, 8)}</span>
              </div>
            </div>
          </div>
          <div className="flex gap-2">
            <button id="download-md" onClick={downloadMarkdown} className="btn-secondary text-xs">
              <Download className="w-3.5 h-3.5" /> Markdown
            </button>
            <button id="download-json" onClick={downloadJson} className="btn-secondary text-xs">
              <Download className="w-3.5 h-3.5" /> JSON
            </button>
          </div>
        </div>
      </div>

      {/* Score + summary */}
      <div className="grid grid-cols-1 lg:grid-cols-5 gap-4">
        <div className="lg:col-span-2"><HealthScoreCard score={healthScore} /></div>
        <div className="lg:col-span-3 card rounded-2xl">
          <h3 className="text-xs text-gray-500 uppercase tracking-wider font-semibold mb-4">Findings Summary</h3>
          <div className="grid grid-cols-3 gap-3 mb-4">
            <SummaryItem label="Testing gaps" value={testGaps.length} color={testGaps.length > 5 ? 'text-orange-400' : 'text-white'} />
            <SummaryItem label="Config issues" value={configHealth.issues.length} color={configHealth.issues.length > 3 ? 'text-yellow-400' : 'text-white'} />
            <SummaryItem label="Critical risks" value={criticalCount} color={criticalCount > 0 ? 'text-red-400' : 'text-green-400'} />
          </div>
          <div className="grid grid-cols-3 gap-3">
            <SummaryItem label="Test files" value={testProfile.totalTestFiles} color="text-purple-400" />
            <SummaryItem label="Test cases" value={testProfile.totalTestCount} color="text-purple-300" />
            <SummaryItem label="High risks" value={highCount} color={highCount > 0 ? 'text-orange-400' : 'text-green-400'} />
          </div>
        </div>
      </div>

      {/* Test health section */}
      {testGaps.length > 0 && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <FlaskConical className="w-4 h-4 text-purple-400" />
            <h3 className="text-sm font-bold text-gray-200">TestPilot Findings</h3>
            <span className="text-xs text-gray-600">{testGaps.length} gaps</span>
          </div>
          <div className="card rounded-2xl divide-y divide-gray-800/50">
            {testGaps.slice(0, 10).map((g) => (
              <div key={g.id} className="flex items-start gap-3 py-3 first:pt-0 last:pb-0">
                <span className={`mt-0.5 flex-shrink-0 ${severityBadgeClass(g.severity)}`}>{g.severity.toUpperCase()}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-gray-200">{g.title}</p>
                  <p className="text-xs text-gray-500 mt-0.5 truncate font-mono">{g.filePath}</p>
                </div>
              </div>
            ))}
            {testGaps.length > 10 && (
              <p className="text-xs text-gray-600 pt-3">… and {testGaps.length - 10} more. Download the full report.</p>
            )}
          </div>
        </div>
      )}

      {/* Config health section */}
      {configHealth.issues.length > 0 && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <Settings2 className="w-4 h-4 text-cyan-400" />
            <h3 className="text-sm font-bold text-gray-200">ConfigDoctor Findings</h3>
            <span className="text-xs text-gray-600">{configHealth.issues.length} issues</span>
          </div>
          <div className="card rounded-2xl divide-y divide-gray-800/50">
            {configHealth.issues.slice(0, 10).map((i) => (
              <div key={i.id} className="flex items-start gap-3 py-3 first:pt-0 last:pb-0">
                <span className={`mt-0.5 flex-shrink-0 ${severityBadgeClass(i.severity)}`}>{i.severity.toUpperCase()}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-gray-200">{i.title}</p>
                  <p className="text-xs text-gray-500 mt-0.5 leading-relaxed line-clamp-1">{i.recommendedFix}</p>
                </div>
              </div>
            ))}
            {configHealth.issues.length > 10 && (
              <p className="text-xs text-gray-600 pt-3">… and {configHealth.issues.length - 10} more. Download the full report.</p>
            )}
          </div>
        </div>
      )}

      {/* Priority findings */}
      {priorityFindings.length > 0 && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <TrendingUp className="w-4 h-4 text-orange-400" />
            <h3 className="text-sm font-bold text-gray-200">Prioritised Findings</h3>
          </div>
          <div className="space-y-2">
            {priorityFindings.map((f) => (
              <div key={f.id} className="card rounded-xl flex items-start gap-4">
                <div className="mt-0.5"><span className={severityBadgeClass(f.level)}>{f.level.toUpperCase()}</span></div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-gray-100 mb-1">{f.title}</p>
                  <p className="text-xs text-gray-400 leading-relaxed mb-2">{f.description}</p>
                  <div className="p-2.5 rounded-lg border border-blue-900/30 bg-blue-950/10">
                    <p className="text-xs text-gray-500 font-medium mb-0.5">Recommendation</p>
                    <p className="text-xs text-gray-300 leading-relaxed">{f.recommendation}</p>
                  </div>
                  <p className="text-xs text-gray-700 mt-2">Impact: {f.estimatedImpact}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Final grade */}
      <div className="relative overflow-hidden rounded-2xl border border-gray-800/60 p-8 text-center"
        style={{ background: 'linear-gradient(135deg, rgba(17,24,39,0.9), rgba(11,17,32,0.95))' }}>
        <div className="absolute inset-0 bg-grid opacity-30" />
        <div className="relative">
          <div className="flex items-center justify-center gap-2 mb-3">
            <Trophy className="w-5 h-5 text-yellow-500" />
            <p className="text-xs text-gray-500 uppercase tracking-wider font-semibold">Final Grade</p>
          </div>
          <p className={`text-[6rem] font-black leading-none tabular-nums ${gradeColor(healthScore.grade)}`}
            style={{ textShadow: `0 0 60px currentColor` }}>
            {healthScore.grade}
          </p>
          <p className="text-sm text-gray-500 mt-2">Overall score: <span className="text-white font-bold">{healthScore.overall}/100</span></p>
          <p className="text-xs text-gray-700 mt-4">
            Doctor Dev · AI Software Health Checker · IBM Bob 2.0 Hackathon 2026
          </p>
        </div>
      </div>
    </div>
  );
}
